### PR TITLE
Add ability to set up ITB CE without testing certificates

### PR DESCRIPTION
**Pull request by brianhlin**
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4278

### CODE REVIEW

**Comment by Mansalu** [comment]
😬

**Comment by Mansalu** [comment]
Sorry, if I caused that.

**Review by Mansalu — APPROVED** [review]
LGTM

**Comment by brianhlin** [comment]
Nope, I was the one polluting the GRACC with non-production records!

**Pull request merged**
