### PR TITLE
Updated Jupyter HTCondor config

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by Mansalu** [comment]
Thank you for the Pull Request!

You will need to increment the `version` field in the Chart.yaml file in order to satisfy the CI tool.

**Comment by rynge** [comment]
Done - please assign Muhammad as a reviewer

**Comment by Mansalu** [comment]
Muhammad has been assigned.

Unfortunately the build is still failing for reasons unrelated to the version. 

You should be able to view the full build log here:
https://jenkins.slateci.io/buildresults/catalog-prs/slate-catalog/PR-321/2-log.txt

**Comment by rynge** [comment]
Don't pin against osg-upcoming. It is a moving target, so the 8.9.5 HTCondor version is no longer available. I told Muhammad to move to 8.9.8.

**Review by muali14 — APPROVED** [review]
Looks good to me. The new condor configurations allow job submission to the central pool.

**Pull request merged**
