### PR TITLE
don't use subpath, for LE certs

### PR DESCRIPTION
**Pull request by LincolnBryant**
This should be all that is needed for LE certs where the container copies the certificate into the right place and chowns it.

I haven't touched the situation where a certificate and key are updated by hand and stored as separate secrets.

### CODE REVIEW

**Comment by brianhlin** [comment]
@LincolnBryant could you make a separate PR for incubator so I can test a container with it?

**Comment by brianhlin** [comment]
This LGTM except we should mount `hostcert.pem` as `mode: 420`

**Review by brianhlin — DISMISSED** [review]
LGTM!

**Review by brianhlin — DISMISSED** [review]

**Review by brianhlin — APPROVED** [review]

**Review by Mansalu — APPROVED** [review]
LGTM

**Pull request merged**
