### PR TITLE
Update Open OnDemand application to latest working version

### PR DESCRIPTION
**Pull request by ike091**

### CODE REVIEW

**Comment by Mansalu** [comment]
There's a lot in here...seemingly mostly to do with postgres?

**Comment by Mansalu** [comment]
Could we split this into a PR for each app

**Comment by ike091** [comment]
Ah that was sloppy, I thought the postgres stuff was on a different branch. I will fix that.

**Comment by Mansalu** [comment]
Builds now. Ready for merge?

**Comment by ike091** [comment]
Should be yes.

**Review by Mansalu — APPROVED** [review]
LGTM

**Pull request merged**
