### PR TITLE
Allow operators to specify an SSH certificate secret (SOFTWARE-4850)

### PR DESCRIPTION
**Pull request by brianhlin**
Needs https://github.com/opensciencegrid/docker-compute-entrypoint/pull/49 to do anything useful but should be safe without it

### CODE REVIEW

**Review by LincolnBryant — COMMENTED** [review]
did you bump the chart version? Jenkins is angry.

**Comment by brianhlin** [comment]
Oops, it's been a while! Fixed.

**Comment by LincolnBryant** [comment]
parse error as well it seems!

```
Error: 1 chart(s) linted, 1 chart(s) failed
[ERROR] templates/: parse error at (osg-hosted-ce/templates/deployment.yaml:70): unexpected "}" in end
```

**Review by LincolnBryant — APPROVED** [review]
all looks good to me

**Comment by brianhlin** [comment]
Don't let managers touch configuration. I think things look green now?

**Pull request merged**
