### PR TITLE
Update default token issuer,subject mappings (SOFTWARE-5123)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by LincolnBryant** [comment]
Looks like Jenkins is unhappy
````
Step 5/15 : RUN curl -s -o /etc/yum.repos.d/htcondor-testing-rhel7.repo https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-testing-rhel7.repo  && echo "priority=10" >>/etc/yum.repos.d/htcondor-testing-rhel7.repo  && rpm --import http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor  && yum -y install condor  && mkdir -p /etc/condor/passwords.d /etc/condor/tokens.d  && yum clean all
 ---> Running in b25438315f6e
HTCondor Testing RPM Repository for Redhat Ente 1.2 MB/s | 638 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Thu Apr 21 03:52:11 2022.
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[91mError: 
 Problem: cannot install the best candidate for the job
  - nothing provides python-requests needed by condor-8.9.8-0.512835.el7.x86_64
  - nothing provides policycoreutils-python needed by condor-8.9.8-0.512835.el7.x86_64
[0mThe command '/bin/sh -c curl -s -o /etc/yum.repos.d/htcondor-testing-rhel7.repo https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-testing-rhel7.repo  && echo "priority=10" >>/etc/yum.repos.d/htcondor-testing-rhel7.repo  && rpm --import http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor  && yum -y install condor  && mkdir -p /etc/condor/passwords.d /etc/condor/tokens.d  && yum clean all' returned a non-zero code: 1
make[2]: *** [incubator/condor-login-condor-login.dummy] Error 1
make[1]: *** [CMakeFiles/incubator-repo.dir/all] Error 2
make: *** [all] Error 2
FAILURE```

**Comment by brianhlin** [comment]
Any updates on the failure @sthapa ? Should I just submit a new PR?

**Comment by LincolnBryant** [comment]
What is the status of this?

**Comment by brianhlin** [comment]
Maybe this failure was transient? Can we just kick the Jenkins run? If not, I can submit a new PR from a different branch

**Comment by LincolnBryant** [comment]
This might be fixed. Let's try to merge it and see what happens.

**Pull request merged**
