### PR TITLE
Reinstate single host cert/key secret (SOFTWARE-4299)

### PR DESCRIPTION
**Pull request by brianhlin**
To support handling of Let's Encrypt certs through
cert-manager (https://cert-manager.io/)

### CODE REVIEW

**Comment by Mansalu** [comment]
Closes #339 ?

**Comment by brianhlin** [comment]
Oh yeah, so it does!

**Comment by Mansalu** [comment]
Do we want to send a notice about this to anyone running CEs? This change will probably break their existing secret.

**Review by bbockelm — APPROVED** [review]
Looks good to me.

Note that if `HostCertKeySecret` is set in addition to `HostCertSecret`, you end up with an invalid configuration but the deployment is created anyway.

**Comment by bbockelm** [comment]
@Mansalu - it appears that this will only cause problems for CEs where both old-style secret and this new-style secret is specified.

**Comment by brianhlin** [comment]
> Do we want to send a notice about this to anyone running CEs? This change will probably break their existing secret.

Nope, the singular secret is a brand new value so installations using the existing `HostCertSecret` and `HostKeySecret` should be unaffected.

> Note that if HostCertKeySecret is set in addition to HostCertSecret, you end up with an invalid configuration but the deployment is created anyway.

I don't think so unless I borked the if/else? It's too bad we can't rely on spacing to make this clearer but here's what I'm trying to do:

```
if HostCertKeySecret:
    # use single secret
else:
    if HostKeySecret:
        # use standalone key secret
    if HostCertSecret:
        # use standalone cert secret
```

**Review by bbockelm — APPROVED** [review]
LGTM.

I don't claim to be an expert in go template syntax, but this appears to be the right logic.

Once it's merged in, I'll be happy to test tonight.

**Review by Mansalu — APPROVED** [review]
LGTM

**Pull request merged**
