### PR TITLE
new options for squid

### PR DESCRIPTION
**Pull request by LincolnBryant**
added new option for minimum object size on disk cache or disabling itt entirely

### CODE REVIEW

**Comment by LincolnBryant** [comment]
I'm not sure what that extra "{{ else }}" block was doing there, so please carefully review this commit because I'm not sure what I may break

**Comment by muali14** [comment]
I just noticed this PR. I think our Slack conversation addresses the main questions and clarifies where the changes should be made. 

Other than that, I think the new options would need to be added to the README and values.yaml file with some comments.

Let me know if missed anything, or have any other questions.

**Comment by LincolnBryant** [comment]
I added a slew of comments and I think reordered things appropriately. Here are some sample configs with various params:

Defaults:
```awk
    # Always set the monitoring IP range
    setoption("acl HOST_MONITOR src", "127.0.0.1/32")
    # Always set the visible hostname
    setoption("visible_hostname", "'`uname -n`'/${process_number}")
    # Whether to rotate logs or not
    setoption("logfile_rotate", "30")
    # If multiple workers are NOT requested, set a single cache dir with one of
    # three options: 
    #  1. Cache with a minimum object size OR
    #  2. Cache with the disk cache disabled entirely OR
    #  3. Cache with no special parameters (default).
    
    setoption("cache_dir", "ufs /var/cache/squid/squid 10000 16 256")
```


Multiple workers, cpu affinity maps, logging disabled:
```awk
    # Always set the monitoring IP range
    setoption("acl HOST_MONITOR src", "127.0.0.1/32")
    # Always set the visible hostname
    setoption("visible_hostname", "'`uname -n`'/${process_number}")
    # Set the CPU affinity map
    setoption("cpu_affinity_map", "process_numbers=1,2,3,4 cores=2,3,4,5")
    # Whether to rotate logs or not
    setoption("logfile_rotate", "30")
    # If multiple workers are requested
    # If multiple workers are used, and logging is disabled:
    setoption("access_log", "none")
    # Set the number of workers and create a cache for each unique worker
    setoption("workers", 4 )
    setoption("cache_dir", "ufs /var/cache/squid/squid${process_number} 10000 16 256")
```

Minimum cache size enabled:
```awk
    # Always set the monitoring IP range
    setoption("acl HOST_MONITOR src", "127.0.0.1/32")
    # Always set the visible hostname
    setoption("visible_hostname", "'`uname -n`'/${process_number}")
    # Whether to rotate logs or not
    setoption("logfile_rotate", "30")
    # If multiple workers are NOT requested, set a single cache dir with one of
    # three options: 
    #  1. Cache with a minimum object size OR
    #  2. Cache with the disk cache disabled entirely OR
    #  3. Cache with no special parameters (default).
    
    setoption("cache_dir", "ufs /var/cache/squid/squid 10000 16 256 min_size=1000000")
```

Disk cache disabled entirely:
```awk
    # Always set the monitoring IP range
    setoption("acl HOST_MONITOR src", "127.0.0.1/32")
    # Always set the visible hostname
    setoption("visible_hostname", "'`uname -n`'/${process_number}")
    # Whether to rotate logs or not
    setoption("logfile_rotate", "30")
    # If multiple workers are NOT requested, set a single cache dir with one of
    # three options: 
    #  1. Cache with a minimum object size OR
    #  2. Cache with the disk cache disabled entirely OR
    #  3. Cache with no special parameters (default).
    
    setoption("cache_dir", "none /var/cache/squid/squid 10000 16 256")
```

**Review by muali14 — APPROVED** [review]
Looks good!

**Comment by LincolnBryant** [comment]
Thanks I will try it out tomorrow!

**Pull request merged**
