### PR TITLE
Moved incubator app FTS3 to the attic.

### PR DESCRIPTION
**Pull request by adamhgriffith-uofu**
See #588 for more details.

### CODE REVIEW

**Comment by LincolnBryant** [comment]
This is fine. I think we can pull this back down out of the attic if we decide to normalize FTS3 against the image we're building in the OSG repos these days.

**Comment by adamhgriffith-uofu** [comment]
Ok, time to check on Jenkins....

**Comment by adamhgriffith-uofu** [comment]
Ah, it is rebuilding everything because of the cache. Ok, so I'll check back in 3 hours.

**Comment by adamhgriffith-uofu** [comment]
This change is now live.

**Pull request merged**
